### ISSUE TITLE
shorter/prettier style for gh issues

### ISSUE THREAD

**Issue by ThomasWaldmann** [jeffwidman/bitbucket-issue-migration#109]
How about this style (just picked a random moin ticket as an example) - it would save that whole footer that has now the link to the bitbucket ticket:

[Originally reported](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/500) by **Orestis Ioannou (Bitbucket: [oorestisime](https://bitbucket.org/oorestisime), GitHub: [oorestisime](https://github.com/oorestisime))**

Markup:

```
[Originally reported](https://bitbucket.org/thomaswaldmann/moin-2.0/issue/500) by 
**Orestis Ioannou (Bitbucket: [oorestisime](https://bitbucket.org/oorestisime), GitHub: [oorestisime](https://github.com/oorestisime))**
```

**Comment by ThomasWaldmann** [comment]
any comments? is a PR for this wanted?

**Comment by ThomasWaldmann** [comment]
Implemented by PR #110. Further improvements could be discussed here (or in a new issue).

**Comment by jeffwidman** [comment]
So I was reading through your example issue at https://github.com/moinwiki/moin/issues/196 and I noticed it's a bit jarring that all the comments start with the distracting header. 

What about putting the *_Originally reported_* down in the footer? 

For comments this seems straightforward since the reader is already aware that the original issue was migrated from BB and so not a surprise that some comments were also migrated.

For issues themselves, I can go either way... I'd still probably lean towards moving the metadata below the issue.

@ThomasWaldmann what do you think?

**Comment by ThomasWaldmann** [comment]
My thoughts leading to the style as in the PR were like this:
- github puts the name of whoever ran the importer at the top left of the issue or comment.
- as this person is often not the person who originally wrote the issue/comment, I wanted to "fix" (document) that at a place close-by - this is why it is in the first line.
- if one would put it into the footer, it could be quite far away for longer body texts.

**Comment by jeffwidman** [comment]
> github puts the name of whoever ran the importer at the top left of the issue or comment.

Oh yeah, I forgot about the cognitive dissonance there. Agree the header is better.
