### ISSUE TITLE
Atomic Issue Creation

### ISSUE THREAD

**Issue by sertel** [jeffwidman/bitbucket-issue-migration#16]
Hi,

since the issue tracker API in github does not provide any transactional semantics the script must make sure that once it has created a new issue in github, it must not fail. Otherwise it will recreate the same issue over and over again when retrying. I ran into encoding problems and experienced exactly this problem.

Suggested change:
def push_issue(gh_username, gh_repository, issue, body, comments):
    #perform formatting before issue creation
    formatted_comments = []
    for comment in comments:
        try:
            formatted_comments.append(format_comment(comment))
        except UnicodeDecodeError as e:
            print "failed comment:", comment, type(comment['user']), type(comment['body'])
            raise
   ...
    # finally use the preformatted comments
    for comment in formatted_comments:
        github.issues.comments.create(
            new_issue.number,
            comment,
            gh_username,
            gh_repository
        )

Cheers,
Sebastian

**Comment by jeffwidman** [comment]
Is this still an issue with the new Github Import API that #25 uses? 

I know the encoding issues were fixed, so that won't cause crashes anymore, but it does make sense that we should be handle errors intelligently so that if something else causes failure we're not creating duplicate issues.

**Comment by jeffwidman** [comment]
I looked into this. 

GitHub's new Import API doesn't let us specify issue IDs or otherwise overwrite existing issues. And there's already the `--start_id` option to restart the import from a specific BB ID (assuming the GitHub ID's before that were created successfully). So I think that's as good as we'll get here for now.

I added a note to the readme: 1b71d11

Also, the Unicode issue that triggered this for you should be fixed by the switch to Python 3.
