### ISSUE TITLE
BB Issue IDs may not match Github Issue IDs if BB issues were deleted

### ISSUE THREAD

**Issue by jeffwidman** [jeffwidman/bitbucket-issue-migration#42]
For example, issue 3 was deleted.

Now the 3rd issue created in Github is BB issue 4, and the IDs get out of sync. 

Non-sync'd IDs breaks `fix_links()` conversion to relative GH urls.

Test it on the SQLAlchemy repo, as IDs and issue total count do not match, so guaranteed to hit this issue. 

I'm not sure how to solve, as Github doesn't let us input the issue ID. Perhaps when it happens, create a placeholder issue in github just to keep the IDs synced. Be sure to auto-close this placeholder issue.

**Comment by jeffwidman** [comment]
This is a legit problem--example: https://bitbucket.org/zzzeek/sqlalchemy/issues/2479

**Comment by jeffwidman** [comment]
Added a test to catch this in 0dc1824cded9ce76677ea8f987baedcc073eee06

**Comment by abadger1406** [comment]
https://github.com/NetFM/c2p

I've made it public so you can see the repeated issue that has been copied

**Comment by abadger1406** [comment]
Managed to workaround my issue by importing into a new github repository, so had no ID's for tickets within it.

**Comment by jeffwidman** [comment]
As noted in https://github.com/jeffwidman/bitbucket-issue-migration/issues/70#issuecomment-176901831, can't just use track the offset here for `fix_links()` because of the following scenario:

1. issue 1 created
2. issue 2 created
3. issue 3 created, and then issue 1 edited to include a reference to issue 3. 
4. issue 2 deleted. 

If I just track an offset, when the link in issue 1 to issue 3 is converted, I won't be aware of the offset created by issue 2 being deleted. 

So best way to resolve is just insert blank placeholder issue.

**Comment by mithrandi** [comment]
I just wanted to point out that it's possible for issues to be non-contiguous even if no issues were deleted; for example, when we originally migrated from Launchpad to BitBucket, we kept the Launchpad bug numbers for everything. Since Launchpad bug numbers are global (a single bug can be associated with multiple projects), our bug numbers start at high number, and have lots and lots of holes.

**Comment by jeffwidman** [comment]
@mithrandi thanks, I was ignorant of that--definitely affects the proposed solution here. Likely I'll need to instead just make the link converter function optional, so that it can be disabled for these scenarios.

Did Bitbucket support specifying the issue ID when you imported over from Launchpad?

**Comment by mithrandi** [comment]
It's been a while since we did the migration to BitBucket (and I can't find the script we wrote to do it), but I believe it was done by preparing the data in a suitable format for the Import/Export feature, [documented here](https://confluence.atlassian.com/bitbucket/issue-import-export-data-format-330796872.html). I don't think you can create an issue through the API with an arbitrary issue ID, but you can specify it in the import data.

By the looks of things, the GitHub issues import API does *not* support this, and creating hundreds of thousands of placeholder issues is obviously not a great idea. Perhaps they would add it if we ask nicely? On the other hand, at least in our particular case, we probably don't care too much about keeping the issue IDs, we mainly did it in the LP→BB migration because we could, not because it was important. (If it wasn't clear, we're looking to migrate from BB→GH now).

**Comment by mithrandi** [comment]
Aha, found it the script: https://bitbucket.org/jonathanj/lp2bb

**Comment by jeffwidman** [comment]
@mithrandi the GitHub issue import API uses a task queue to process/import tasks, they're not immediately created. So I doubt they'd add support for specifying IDs, as it'd likely require changing their whole infrastructure underlying issue importing. 

The easier thing to do is likely to create a mapping of issue IDs in BB to expected ID in GitHub. This mapping should also account for existing issues in the GH destination repo (#70). Then run the import (and hope that nobody files a new issue during the import process... probably add a note to the docs encouraging folks who really care to start with blank repo, and only migrate the code if the issues migrate successfully, otherwise to redo the issue import).

Also could make `fix_links()` controlled by an optional flag on teh command line, defaulting to enabled, but that way people disable if desired. Personally, I think it's extremely convenient to run `fix_links()` in the repo.

**Comment by mithrandi** [comment]
You should probably include the original BB ID somewhere in the migrated issue at least, since this may appear elsewhere (eg. in VCS commits that were migrated).

**Comment by jaraco** [comment]
I encountered this issue today attempting to [migrate CherryPy](https://bitbucket.org/cherrypy/cherrypy/issues/1410/migrate-to-github) with a [missing issue](https://bitbucket.org/cherrypy/cherrypy/issues/277).

**Comment by HebronNor** [comment]
@jaraco Thanks for your work on filling gaps, work beautifully :)
