### ISSUE TITLE
Migration script unnecessarily prompts for Github creds on dry run

### ISSUE THREAD

**Issue by jaraco** [jeffwidman/bitbucket-issue-migration#53]
During a dry run, Github credentials are not needed, but they're prompted for anyway. This was not an issue in the refactor-and-python3 submission, which only prompted for credentials in the SubmitHandler.

**Comment by jeffwidman** [comment]
Yeah, I thought about taking it out, but I'm planning to build #46 into `format_user()` and I have a hunch the creds are needed to avoid ratelimiting when checking GitHub's username API: 
https://developer.github.com/v3/#rate-limiting

I also considered bypassing the username check for `--dry-run`, but in general I'm trying to make it so all issue/comment formatting code runs the same regardless of whether it's a dry-run or not.... there were a number of bugs when I took over maintenance because dry-run was kinda hacked in there and didn't always execute the same formatting code.

**Comment by jaraco** [comment]
Sounds good
