### ISSUE TITLE
Uncaught exception when Keyring installed but doesn't find GH/BB creds...

### ISSUE THREAD

**Issue by abadger1406** [jeffwidman/bitbucket-issue-migration#60]
Hi Jeff,

Probably doing something very wrong, but how do I save my
username/password so that it works with the utility ?

have tried putting in ~/.hgrc - see below.

Thanks Dave

ps Use to Climb in UK - Chair Ladder was my favourite area, Cornwall
granite sea cliff climbing.

(py3) dave$ python3 migrate.py dave@netfm.org
https://bitbucket.org/abadger/c2p abadger1406
https://github.com/NetFM/c2p
Traceback (most recent call last):
  File "migrate.py", line 442, in <module>
    sys.exit(main(options))
  File "migrate.py", line 103, in main
    kr_pass_bb = keyring.get_password('Bitbucket', options.bitbucket_username)
  File "/home/dave/py3/lib/python3.4/site-packages/keyring/core.py",
line 42, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/home/dave/py3/lib/python3.4/site-packages/keyring/backends/fail.py",
line 18, in get_password
    raise RuntimeError("No recommended password was available")
RuntimeError: No recommended password was available

(py3) dave$ more ~/.hgrc-
[auth]
x.prefix  = https://bitbucket.org/abadger/c2p
x.username = dave@netfm.org
x.password = xxx-password-xxx

(py3) dave$

**Comment by jeffwidman** [comment]
We don't pass the passwords in as a command line option for security reasons. So the two places the password can go is either your system keychain or if it's not found, the script will ask you for the password. `~/.htrc` is definitely not the correct place, and actually won't do anything at all. 

I haven't used the `keyring` lib myself... @jaraco does this error indicate he's got the python lib `keyring` installed, but it's not finding any GH/BB creds in the keyring? If so, should we be catching this error and dropping back to manually prompting or is there a better way? 

In the meantime @abadger1406 as a workaround, I suggest uninstalling the keyring lib: `pip uninstall keyring` and then re-running the script... it will realize keyring isn't installed and prompt you for the passwords then.

**Comment by igorsantos07** [comment]
Same here, except my error says "no recommended backend was available".

I'm running Ubuntu 14.04 here, and had to install pip3 in my machine - only had Python 3. Additionally, I don't think I even use the system keychain - maybe it's not setup at all, and thus it issued that message? If that's indeed the case, I guess the script should silently fail and prompt for password.

Finally, from pure interpretation I guess what you said is right: the @abadger1406 error means the keyring do not have the GH/BB passwords.

**Comment by jeffwidman** [comment]
This sounds like a separate issue--likely as you say the system keychain simply isn't setup--but I'm not too familiar with the keyring library. Hopefully @jaraco can explain a little more of what's happening here?

**Comment by jaraco** [comment]
Ugh.

So keyring 8.0 removes a bunch of non-preferred backends, which means it may be possible that there is no valid backend available, leading to the error message (which itself erroneously referenced 'preferred password' instead of 'preferred backend' until 8.0.1).

See https://github.com/jaraco/keyring/issues/117 for a history leading to the 8.0 release.

**Comment by jeffwidman** [comment]
1. For the first issue above--where he seems to have an available backend, any idea why Keyring throws an exception rather than returning None when GH/BB creds weren't available? 

2. When a preferred backend isn't available, sounds like we just need to catch the exception. I also have no problem with requiring `keyring >= 8.0.1`. 

I'm a little surprised keyring throws an exception rather than just returning None when no backend is available... I guess it makes sense in other contexts to know why it's explicitly failing, but in this context, all we need is just try to grab the creds, and if they aren't available, then revert to manually asking the user--doesn't matter to us if they aren't available due to no backend or no creds.

**Comment by jaraco** [comment]
The quick workaround is to also install `keyring.alt` which will bring in the non-preferred backends and one of them will return None for the call to `get_password`, allowing the script to prompt for the password and continue.

**Comment by jaraco** [comment]
If you would just pull that commit, I expect it fixes the issue with minimal fuss. Assuming it works well, I'll make it a formal recommendation for other projects moving forward.

**Comment by jaraco** [comment]
Let me know if I should send a PR with it.

**Comment by jeffwidman** [comment]
Thanks @jaraco really appreciate you willing to help maintain the keyring implementation here. 

I didn't test it myself, but it makes sense in theory and since this should error in an obvious way, I'm fine with assuming it works and then dealing with any issues that crop up.
