### ISSUE TITLE
"... offset the imported issue IDs by the correct amount."

### ISSUE THREAD

**Issue by ozgurakgun** [jeffwidman/bitbucket-issue-migration#80]
"If you are migrating to a GitHub repo with existing issues, just edit the code to offset the imported issue IDs by the correct amount."

Can someone tell me how to go about doing this please?

Also: Would it make sense to make the offset a command line argument?

Thanks!

**Comment by jaraco** [comment]
> Can someone tell me how to go about doing this please?

I think that statement might no longer be correct. The way I read it, everything should work just fine except maybe for the [check for alignment](https://github.com/jeffwidman/bitbucket-issue-migration/blob/master/migrate.py#L195) which you could adapt with an offset or simply disable.

> Would it make sense to make the offset a command line argument?

Maybe, although getting it right might be difficult.

In my experience, you probably don't want to import issues into a repository with existing issues, because if anything goes wrong with the import, there's no way to undo.

**Comment by ozgurakgun** [comment]
My use case is actually importing from 2 bitbucket repos into one github. I admit that this is not the best idea, but in my case it would be nice if I could get it to work.

I am running into #65 so experimenting is a bit hard. I will report what happens when I comment-out the assertion you link to.

**Comment by jeffwidman** [comment]
Yep, what @jaraco said. I've looked several times at trying to add workarounds to handle some of the edgecases around issue numbering, and every time I throw my hands up in frustration. 

The code is pretty straightforward right now, and trying to handle some of these weird edge cases (especially due to the complications of #65) just makes life a royal pain. 

The most common use case is migrating to a fresh repo, and there it's possible to retry the migration until you get one that doesn't encounter #65. So I've left as is. 

Plus, if you need to handle something weird, such as migrating two repos, it's easy enough to do some quick modifications--the code should be pretty straightforward and well-commented.

**Comment by ozgurakgun** [comment]
You are right, the code is quite straightforward. I am now repeatedly running into #65, but other than that I think I can hack my way through this.

Thanks @jeffwidman and @jaraco!
