### ISSUE TITLE
Fails to migrate isses with pictures

### ISSUE THREAD

**Issue by intbots** [jeffwidman/bitbucket-issue-migration#81]
When issues have pictures embedded on them in the comment sections, it causes runtime error.

**Comment by jeffwidman** [comment]
1) What is the stacktrace?

2) Do you have a public repo that can replicate the issue against?

3) Failing that, can you send me the HTML that's int eh comment so I can see how BB is embedding the image? Feel free to sanitize the actual text/image filename, I just need to see the structure.

**Comment by intbots** [comment]
I am not able replicate the issue with a test repo. What happens is the image display on a particular issue breaks on github and it gives Invalid upstream response (403) when i click on it.

I created a test repo https://bitbucket.org/infinitei/test_repo but surprisingly I am not able to recreate the problem now.

This is the stacktrace when I used it on my actual repo i wanted to transfer.

`Completed 29 of 83 issues
Traceback (most recent call last):
  File "migrate.py", line 490, in <module>
    sys.exit(main(options))
  File "migrate.py", line 190, in main
    status_url, options.gh_auth, headers).json()['issue_url']
  File "migrate.py", line 477, in verify_github_issue_import_finished
    .format(respo.json())
RuntimeError: Failed to import GitHub issue due to the following errors:
{'repository_url': 'https://api.github.com/repos/intbots/Naksha', 'url': 'https://api.github.com/repos/intbots/Naksha/import/issues/1066399', 'created_at': '2017-02-08T10:57:58-05:00', 'id': 1066399, 'errors': [{'resource': 'Internal Error', 'code': 'error', 'value': '46148d878f6426a6e35bef76ad5f71b269f87c5b', 'field': None, 'location': 'n/a'}], 'status': 'failed', 'import_issues_url': 'https://api.github.com/repos/intbots/Naksha/import/issues', 'updated_at': '2017-02-08T10:58:29-05:00'}
`

**Comment by jeffwidman** [comment]
That stacktrace doesn't say anything about the image breaking... it just says the import is failing in the Github URL. 

This is different than the error you described, which implies the import succeeded, but the embed failed to load. 

403 is forbidden, so the image URL won't load. Doublecheck the html to see if the URL for the image embed is the same on GH and BB... it they're the same, then it's probably failing because the image host is trying to prevent images from being hotlinked/remote embedded. That would have nothing to do with the importer.
